# Generated by Django 6.0.4 on 2026-04-13 17:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MerchantAccount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('merchant_id', models.IntegerField()),
                ('currency', models.CharField(max_length=3)),
                ('account_number', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='PostingLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('merchant_id', models.CharField(max_length=50)),
                ('account_number', models.CharField(max_length=50)),
                ('amount_original', models.DecimalField(decimal_places=2, max_digits=12)),
                ('currency', models.CharField(max_length=3)),
                ('amount_kgs', models.DecimalField(decimal_places=2, max_digits=12)),
                ('post_date', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(default='Success', max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Terminal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('device_code', models.CharField(max_length=50, unique=True, verbose_name='Код устройства')),
                ('merchant_id', models.IntegerField(verbose_name='ID Мерчанта')),
            ],
        ),
        migrations.CreateModel(
            name='TransactionLoad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('external_id', models.CharField(max_length=100, unique=True)),
                ('device_code', models.CharField(max_length=50)),
                ('oper_date', models.DateTimeField()),
                ('amount', models.DecimalField(decimal_places=2, max_digits=15)),
                ('currency', models.CharField(max_length=3)),
                ('card_number', models.CharField(max_length=20)),
                ('status', models.CharField(default='New', max_length=50)),
                ('load_date', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
