# Generated by Django 6.0.4 on 2026-04-17 22:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('host_module', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='postinglog',
            name='merchant_id',
            field=models.IntegerField(verbose_name='ID Мерчанта'),
        ),
    ]
