# Generated by Django 6.0.4 on 2026-05-18 12:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('host_module', '0002_alter_postinglog_merchant_id'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='merchantaccount',
            options={'verbose_name': 'Счет мерчанта', 'verbose_name_plural': '2. Расчетные счета мерчантов'},
        ),
        migrations.AlterModelOptions(
            name='postinglog',
            options={'verbose_name': 'Проводка в АБС', 'verbose_name_plural': '4. Реестр проводок в АБС'},
        ),
        migrations.AlterModelOptions(
            name='terminal',
            options={'verbose_name': 'Терминал', 'verbose_name_plural': '1. Справочник терминалов'},
        ),
        migrations.AlterModelOptions(
            name='transactionload',
            options={'verbose_name': 'Загруженная транзакция', 'verbose_name_plural': '3. Буфер транзакций МПЦ'},
        ),
        migrations.AlterField(
            model_name='merchantaccount',
            name='account_number',
            field=models.CharField(max_length=20, verbose_name='Номер расчетного счета'),
        ),
        migrations.AlterField(
            model_name='merchantaccount',
            name='currency',
            field=models.CharField(max_length=3, verbose_name='Валюта счета'),
        ),
        migrations.AlterField(
            model_name='merchantaccount',
            name='merchant_id',
            field=models.IntegerField(verbose_name='ID Мерчанта'),
        ),
        migrations.AlterField(
            model_name='postinglog',
            name='account_number',
            field=models.CharField(max_length=50, verbose_name='Номер счета зачисления'),
        ),
        migrations.AlterField(
            model_name='postinglog',
            name='amount_kgs',
            field=models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Сумма проводки (KGS)'),
        ),
        migrations.AlterField(
            model_name='postinglog',
            name='amount_original',
            field=models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Сумма в валюте операции'),
        ),
        migrations.AlterField(
            model_name='postinglog',
            name='currency',
            field=models.CharField(max_length=3, verbose_name='Оригинальная валюта'),
        ),
        migrations.AlterField(
            model_name='postinglog',
            name='post_date',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Дата формирования проводки'),
        ),
        migrations.AlterField(
            model_name='postinglog',
            name='status',
            field=models.CharField(default='Success', max_length=20, verbose_name='Статус АБС'),
        ),
        migrations.AlterField(
            model_name='transactionload',
            name='amount',
            field=models.DecimalField(decimal_places=2, max_digits=15, verbose_name='Сумма'),
        ),
        migrations.AlterField(
            model_name='transactionload',
            name='card_number',
            field=models.CharField(max_length=20, verbose_name='Номер карты (маскированный)'),
        ),
        migrations.AlterField(
            model_name='transactionload',
            name='currency',
            field=models.CharField(max_length=3, verbose_name='Валюта'),
        ),
        migrations.AlterField(
            model_name='transactionload',
            name='device_code',
            field=models.CharField(max_length=50, verbose_name='Код устройства'),
        ),
        migrations.AlterField(
            model_name='transactionload',
            name='external_id',
            field=models.CharField(max_length=100, unique=True, verbose_name='Внешний ID транзакции'),
        ),
        migrations.AlterField(
            model_name='transactionload',
            name='load_date',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Дата импорта файла'),
        ),
        migrations.AlterField(
            model_name='transactionload',
            name='oper_date',
            field=models.DateTimeField(verbose_name='Дата и время операции'),
        ),
        migrations.AlterField(
            model_name='transactionload',
            name='status',
            field=models.CharField(default='New', max_length=50, verbose_name='Статус обработки'),
        ),
        migrations.AlterUniqueTogether(
            name='merchantaccount',
            unique_together={('merchant_id', 'currency')},
        ),
    ]
