# Generated by Django 6.0.4 on 2026-05-18 13:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('host_module', '0003_alter_merchantaccount_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExchangeRate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('currency', models.CharField(max_length=3, verbose_name='Currency')),
                ('rate', models.DecimalField(decimal_places=4, max_digits=10, verbose_name='Rate')),
                ('date', models.DateField(verbose_name='Date')),
            ],
            options={
                'verbose_name': 'Курс валюты',
                'verbose_name_plural': '3. Exchange Rates (Курсы НБКР)',
                'unique_together': {('currency', 'date')},
            },
        ),
        migrations.CreateModel(
            name='PostingsLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transaction_ref', models.CharField(max_length=100, verbose_name='Transaction Ref')),
                ('merchant_id', models.IntegerField(verbose_name='Merchant ID')),
                ('account_number', models.CharField(max_length=50, verbose_name='Account Number')),
                ('amount_original', models.DecimalField(decimal_places=2, max_digits=15, verbose_name='Amount Original')),
                ('currency', models.CharField(max_length=3, verbose_name='Currency')),
                ('sum_kgs_equiv', models.DecimalField(decimal_places=2, max_digits=15, verbose_name='Sum KGS Equiv')),
                ('post_date', models.DateTimeField(auto_now_add=True, verbose_name='Post Date')),
                ('status', models.CharField(default='PENDING', max_length=20, verbose_name='Status')),
            ],
            options={
                'verbose_name': 'Проводка в АБС',
                'verbose_name_plural': '5. Postings Log (Реестр АБС)',
            },
        ),
        migrations.CreateModel(
            name='TransactionsLoad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('external_id', models.CharField(max_length=100, unique=True, verbose_name='External ID')),
                ('device_code', models.CharField(max_length=50, verbose_name='Device Code')),
                ('oper_date', models.DateTimeField(verbose_name='Oper Date Time')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=15, verbose_name='Amount')),
                ('currency', models.CharField(max_length=3, verbose_name='Currency')),
                ('card_number', models.CharField(max_length=20, verbose_name='Card Number')),
                ('status', models.CharField(default='New', max_length=50, verbose_name='Status')),
                ('load_date', models.DateTimeField(auto_now_add=True, verbose_name='Load Date')),
            ],
            options={
                'verbose_name': 'Транзакция буфера',
                'verbose_name_plural': '4. Transactions Load (Буфер МПЦ)',
            },
        ),
        migrations.DeleteModel(
            name='PostingLog',
        ),
        migrations.DeleteModel(
            name='TransactionLoad',
        ),
        migrations.AlterModelOptions(
            name='merchantaccount',
            options={'verbose_name': 'Счет мерчанта', 'verbose_name_plural': '2. Merchant Accounts (Счета мерчантов)'},
        ),
        migrations.AlterModelOptions(
            name='terminal',
            options={'verbose_name': 'Терминал', 'verbose_name_plural': '1. Terminals (Справочник устройств)'},
        ),
        migrations.AlterField(
            model_name='merchantaccount',
            name='account_number',
            field=models.CharField(max_length=20, verbose_name='Account Number'),
        ),
        migrations.AlterField(
            model_name='merchantaccount',
            name='currency',
            field=models.CharField(max_length=3, verbose_name='Currency'),
        ),
        migrations.AlterField(
            model_name='merchantaccount',
            name='merchant_id',
            field=models.IntegerField(verbose_name='Merchant ID'),
        ),
        migrations.AlterField(
            model_name='terminal',
            name='device_code',
            field=models.CharField(max_length=50, unique=True, verbose_name='Device Code'),
        ),
        migrations.AlterField(
            model_name='terminal',
            name='merchant_id',
            field=models.IntegerField(verbose_name='Merchant ID'),
        ),
    ]
