# Generated by Django 6.0.4 on 2026-05-18 16:01

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('host_module', '0004_exchangerate_postingslog_transactionsload_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='postingslog',
            name='post_date',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Post Date'),
        ),
    ]
